name: CI and Deploy to cPanel

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Check out the code
        uses: actions/checkout@v4

      # Install dependencies and build the project
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # Deploy to cPanel (Static Files)
      - name: Deploy to cPanel
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.CPANEL_SSH_KEY }}
          REMOTE_HOST: "webhost.bdren.net.bd"
          REMOTE_USER: "bauedu"  # Replace with your actual cPanel username
          TARGET: "~/public_html/darahat"  # Ensure this matches your target directory on cPanel
        with:
          source: ".output/public/*"  # Points to the static build output of Nuxt
          remote_port: "2083"  # Replace "2222" with the correct port if it's not 22

