name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t nuxtpractice .

      - name: Run build command inside Docker
        run: docker run --rm nuxtpractice

      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Test SSH Connection with Key
        env:
          SERVER: ${{ secrets.MY_SERVER_IP }}
          USERNAME: ${{ secrets.SERVER_USERNAME }}
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ env.USERNAME }}@${{ env.SERVER }} "echo 'SSH connection successful'"
