name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t nuxtpractice .

      - name: Run build command inside Docker
        run: docker run --rm nuxtpractice

      - name: Check Secret Variables (Debug)
        run: |
          echo "Server IP: ${{ secrets.MY_SERVER_IP }}"
          echo "Username: ${{ secrets.SERVER_USERNAME }}"
          echo "Password Length: ${{secrets.SERVER_PASSWORD}}"

      - name: Deploy build files to AlmaLinux server
        env:
          SERVER: ${{ secrets.MY_SERVER_IP }}
          USERNAME: ${{ secrets.SERVER_USERNAME }}
          PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          rsync -avz --delete ./build/ ${{ env.USERNAME }}@${{ env.SERVER }}:/home/nuxtproject/
