name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      # Step 3: Build Docker image
      - name: Build Docker image
        run: docker build -t nuxtpractice .

      # Step 4: Save Docker image to a .tar file
      - name: Save Docker image to file
        run: docker save -o nuxtpractice.tar nuxtpractice

      # Step 5: Set up SSH key for secure connection to server
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "${{ secrets.SERVER_IP }}" >> ~/.ssh/known_hosts

      # Step 6: Copy Docker image file to the remote server
      - name: Copy Docker image to server
        run: |
          scp -i ~/.ssh/id_ed25519 nuxtpractice.tar ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/${{ secrets.SERVER_USER }}/nuxtpractice.tar

      # Step 7: Clean up local Docker image file
      - name: Remove local image file
        run: rm nuxtpractice.tar

      # Step 8: Load and run Docker image on the remote server
      - name: Deploy on server
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            # Load Docker image from file
            docker load -i /home/${{ secrets.SERVER_USER }}/nuxtpractice.tar
            # Remove existing container if any
            docker rm -f nuxtpractice || true
            # Run the container
            docker run -d -p 3000:3000 --name nuxtpractice nuxtpractice
            # Remove the Docker image file after loading
            rm /home/${{ secrets.SERVER_USER }}/nuxtpractice.tar
          EOF
