name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t nuxtpractice .

      - name: Run build command inside Docker
        run: docker run --rm nuxtpractice

      - name: Copy SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Add server to known host
        run: ssh-keyscan -H 103.90.2.3 >> ~/.ssh/known_hosts

      - name: Deploy build to servers
        run: |
          scp -r .output/public root@103.90.2.3:/home/nuxtpractice
